[package]
name = "solana_vote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.18.25"
solana-program = "1.18.25"
once_cell = "1.10.0"
